from __future__ import annotations

from prostanet.domains.evidence_registry.models import GuidelineMetadata, ModuleEvidence
from prostanet.shared.contracts import EvidenceCitation


def citation(
    citation_id: str,
    title: str,
    guideline_or_trial: str,
    source_tier: str,
    *,
    document_id: str = "",
    evidence_role: str = "",
    license_class: str = "",
    doi_or_url: str = "",
    local_pdf_path: str = "",
    disease_state: str = "",
    line_of_therapy: str = "",
    biomarker_scope: str = "",
    symptom_scope: str = "",
    toxicity_scope: str = "",
    followup_implications: str = "",
    supports_rule_ids: list[str] | None = None,
    applies_to_modules: list[str] | None = None,
    derived_rule_ids: list[str] | None = None,
    field_implications: list[str] | None = None,
    ui_surfaces: list[str] | None = None,
) -> dict:
    resolved_rule_ids = derived_rule_ids or supports_rule_ids or []
    return EvidenceCitation(
        citation_id=citation_id,
        title=title,
        guideline_or_trial=guideline_or_trial,
        source_tier=source_tier,
        document_id=document_id,
        evidence_role=evidence_role,
        license_class=license_class,
        doi_or_url=doi_or_url,
        local_pdf_path=local_pdf_path,
        disease_state=disease_state,
        line_of_therapy=line_of_therapy,
        biomarker_scope=biomarker_scope,
        symptom_scope=symptom_scope,
        toxicity_scope=toxicity_scope,
        followup_implications=followup_implications,
        supports_rule_ids=supports_rule_ids or resolved_rule_ids,
        applies_to_modules=applies_to_modules or [],
        derived_rule_ids=resolved_rule_ids,
        field_implications=field_implications or [],
        ui_surfaces=ui_surfaces or [],
    ).to_dict()


def _document_registry(*documents: dict) -> dict[str, dict]:
    return {document["document_id"]: document for document in documents if document.get("document_id")}


GUIDELINES = {
    "nccn_2026": GuidelineMetadata(
        guideline="NCCN",
        version="5.2026",
        effective_date="2026-01-23",
        source_type="pdf",
        source_ref="/Users/oscaralvarado/Desktop/NCCN 2026.pdf",
        summary="Fuente normativa primaria para la estructura de los asistentes clínicos, la estadificación, la recurrencia, la segunda recurrencia bioquímica y la enfermedad avanzada.",
    ),
    "eau_2026": GuidelineMetadata(
        guideline="EAU",
        version="2026",
        effective_date="2026-03-01",
        source_type="pdf",
        source_ref="/Users/oscaralvarado/Desktop/EAU-EANM-ESTRO-ESUR-ISUP-SIOG-Guidelines-on-Prostate-Cancer-2026.pdf",
        summary="Capa comparativa paralela para clasificación, seguimiento, calidad de vida, enfermedad avanzada y cuidados paliativos frente a la Red Nacional Integral del Cáncer (NCCN) 2026.",
    ),
}

NCCN_PRIMARY = citation(
    "nccn_prostate_5_2026",
    "NCCN Clinical Practice Guidelines in Oncology: Prostate Cancer. Version 5.2026.",
    "NCCN 5.2026",
    "guideline_primary",
    document_id="nccn_2026",
    evidence_role="primary_guideline",
    license_class="licensed_guideline_pdf",
    local_pdf_path="/Users/oscaralvarado/Desktop/NCCN 2026.pdf",
    disease_state="Transversal",
    followup_implications="Define la recomendación principal, la jerarquía terapéutica y la estructura de monitoreo por estado clínico.",
    supports_rule_ids=["all.nccn_primary"],
    applies_to_modules=[
        "diagnostic_workup",
        "post_negative_biopsy_followup",
        "localized_initial",
        "post_prostatectomy",
        "recurrence_bcr",
        "adt_progression_verification",
        "mcspc_oligo_metachronous",
        "mcspc_low_volume_sync_oligo",
        "mcspc_high_volume_sync",
        "mcspc_high_volume_metachronous",
        "mcspc_high_volume",
        "m0_crpc",
        "m1_crpc",
    ],
    field_implications=["guideline_versions", "primary_recommendation"],
    ui_surfaces=["wizard.sidebar", "wizard.results", "patient_profile", "dashboard"],
)

EAU_PRIMARY = citation(
    "eau_prostate_2026",
    "EAU-EANM-ESTRO-ESUR-ISUP-SIOG Guidelines on Prostate Cancer 2026.",
    "EAU 2026",
    "guideline_comparator",
    document_id="eau_2026",
    evidence_role="primary_guideline",
    license_class="licensed_guideline_pdf",
    local_pdf_path="/Users/oscaralvarado/Desktop/EAU-EANM-ESTRO-ESUR-ISUP-SIOG-Guidelines-on-Prostate-Cancer-2026.pdf",
    disease_state="Transversal",
    followup_implications="Aporta comparación estructurada en diagnóstico, seguimiento, calidad de vida, transición entre estados y cuidados paliativos.",
    supports_rule_ids=["all.eau_comparison"],
    applies_to_modules=[
        "diagnostic_workup",
        "post_negative_biopsy_followup",
        "localized_initial",
        "post_prostatectomy",
        "recurrence_bcr",
        "adt_progression_verification",
        "mcspc_oligo_metachronous",
        "mcspc_low_volume_sync_oligo",
        "mcspc_high_volume_sync",
        "mcspc_high_volume_metachronous",
        "mcspc_high_volume",
        "m0_crpc",
        "m1_crpc",
    ],
    field_implications=["guideline_versions", "comparison_layer"],
    ui_surfaces=["wizard.sidebar", "wizard.results", "patient_profile"],
)

ACTIVE_SURVEILLANCE_REAL_WORLD = citation(
    "olsson_active_surveillance_2020",
    "Intensity of Active Surveillance and Transition to Treatment in Men with Low-risk Prostate Cancer.",
    "Olsson 2020",
    "supporting_study",
    document_id="olsson_2020_active_surveillance",
    evidence_role="real_world",
    license_class="publisher_pdf",
    doi_or_url="https://doi.org/10.1016/j.euo.2019.05.005",
    local_pdf_path="/Users/oscaralvarado/Desktop/4.pdf",
    disease_state="Localized low-risk",
    followup_implications="Apoya la intensidad de vigilancia activa y la interpretación de la transición desde vigilancia activa hacia tratamiento curativo.",
    supports_rule_ids=["localized_initial.active_surveillance_followup"],
    applies_to_modules=["localized_initial"],
    field_implications=["confirmatory_biopsy_planned", "baseline_qol", "genomic_classifier"],
    ui_surfaces=["wizard.sidebar", "wizard.results", "patient_profile"],
)

BENIGN_BIOPSY_LONG_TERM = citation(
    "palmstedt_benign_biopsy_2019",
    "Long-term Outcomes for Men in a Prostate Screening Trial with an Initial Benign Prostate Biopsy: A Population-based Cohort.",
    "Palmstedt 2019",
    "supporting_study",
    document_id="palmstedt_2019_negative_biopsy",
    evidence_role="real_world",
    license_class="publisher_pdf",
    doi_or_url="https://doi.org/10.1016/j.euo.2019.01.016",
    local_pdf_path="/Users/oscaralvarado/Desktop/5.pdf",
    disease_state="Post-negative biopsy follow-up",
    followup_implications="Sustenta un seguimiento de baja intensidad tras biopsia benigna cuando la densidad del antígeno prostático específico y la sospecha clínica permanecen bajas.",
    supports_rule_ids=["post_negative_biopsy_followup.low_intensity_followup"],
    applies_to_modules=["post_negative_biopsy_followup"],
    field_implications=["repeat_biopsy_trigger", "prior_biopsy_count", "psa_kinetics"],
    ui_surfaces=["wizard.sidebar", "wizard.results"],
)

LATE_RT_TOXICITY = citation(
    "irradiate_reply_2026",
    "Re: Real-World Burden and Management of Late Genitourinary Toxicity After Prostate RT: Insights from IRRADIaTE.",
    "IRRADIaTE 2026",
    "supporting_study",
    document_id="irradiate_2026_late_rt_toxicity",
    evidence_role="safety_signal",
    license_class="publisher_pdf",
    doi_or_url="https://doi.org/10.1016/j.euo.2026.02.022",
    local_pdf_path="/Users/oscaralvarado/Desktop/1.pdf",
    disease_state="Post-radiotherapy survivorship",
    toxicity_scope="Toxicidad genitourinaria tardía tras radioterapia",
    followup_implications="Refuerza la necesidad de seguimiento prolongado de toxicidad urinaria tardía tras radioterapia definitiva o de rescate.",
    supports_rule_ids=["localized_initial.radiotherapy_survivorship", "recurrence_bcr.salvage_radiotherapy_toxicity"],
    applies_to_modules=["localized_initial", "recurrence_bcr"],
    field_implications=["baseline_bowel_qol", "baseline_urinary_qol"],
    ui_surfaces=["wizard.results", "patient_profile"],
)

PROPEL_SYMPTOMATIC = citation(
    "propel_symptomatic_subgroups_2025",
    "Efficacy and Safety of Olaparib Plus Abiraterone Versus Placebo Plus Abiraterone in the First-line Treatment of Patients with Asymptomatic/Mildly Symptomatic and Symptomatic Metastatic Castration-resistant Prostate Cancer: Analyses from the Phase 3 PROpel Trial.",
    "PROpel symptomatic subgroup analysis",
    "supporting_study",
    document_id="propel_symptomatic_2025",
    evidence_role="supportive_trial",
    license_class="publisher_pdf",
    doi_or_url="https://doi.org/10.1016/j.euo.2024.09.013",
    local_pdf_path="/Users/oscaralvarado/Desktop/2.pdf",
    disease_state="Metastatic castration-resistant disease",
    line_of_therapy="First line",
    biomarker_scope="Combinación de olaparib con abiraterona",
    symptom_scope="Pacientes asintomáticos, levemente sintomáticos y sintomáticos",
    followup_implications="Aporta contexto de subgrupos sintomáticos y tolerabilidad para la combinación olaparib más abiraterona, sin reemplazar la jerarquía primaria de las guías.",
    supports_rule_ids=["m1_crpc.propel_context"],
    applies_to_modules=["m1_crpc"],
    field_implications=["pain_symptoms", "baseline_qol"],
    ui_surfaces=["wizard.sidebar", "wizard.results"],
)

CARD_TRIAL = citation(
    "card_2019_cabazitaxel",
    "Cabazitaxel versus Abiraterone or Enzalutamide in Metastatic Prostate Cancer.",
    "CARD",
    "supporting_study",
    document_id="doc_33_card",
    evidence_role="supportive_trial",
    license_class="publisher_pdf",
    doi_or_url="https://doi.org/10.1056/NEJMoa1911206",
    local_pdf_path="/Users/oscaralvarado/Desktop/33.pdf",
    disease_state="M1 CRPC",
    line_of_therapy="Post-docetaxel and prior ARPI",
    followup_implications="Prioriza cabazitaxel frente a una nueva secuencia ARPI-ARPI cuando ya hubo docetaxel y progresión temprana en ARPI.",
    supports_rule_ids=["m1_crpc.card_cabazitaxel_preference"],
    applies_to_modules=["m1_crpc"],
    field_implications=["prior_therapy", "prior_docetaxel_cycles", "current_sequence_goal"],
    ui_surfaces=["wizard.sidebar", "wizard.results", "patient_profile"],
)

VISION_TRIAL = citation(
    "vision_2021_lu177_psma",
    "Lutetium-177-PSMA-617 for Metastatic Castration-Resistant Prostate Cancer.",
    "VISION",
    "supporting_study",
    document_id="doc_34_vision",
    evidence_role="supportive_trial",
    license_class="publisher_pdf",
    doi_or_url="https://doi.org/10.1056/NEJMoa2107322",
    local_pdf_path="/Users/oscaralvarado/Desktop/34.pdf",
    disease_state="M1 CRPC",
    line_of_therapy="Post-ARPI with taxane exposure",
    biomarker_scope="PSMA-positive disease with imaging selection",
    followup_implications="Estructura elegibilidad para lutecio-177 PSMA-617 y exige positividad PSMA sin lesiones dominantes PSMA-negativas clínicamente relevantes.",
    supports_rule_ids=["m1_crpc.vision_psma_eligibility"],
    applies_to_modules=["m1_crpc"],
    field_implications=["psma_positive", "psma_negative_dominant_lesions", "biomarker_source"],
    ui_surfaces=["wizard.sidebar", "wizard.results", "patient_profile"],
)

PROFOUND_TRIAL = citation(
    "profound_2020_olaparib",
    "Survival with Olaparib in Metastatic Castration-Resistant Prostate Cancer.",
    "PROfound",
    "supporting_study",
    document_id="doc_35_profound",
    evidence_role="supportive_trial",
    license_class="publisher_pdf",
    doi_or_url="https://doi.org/10.1056/NEJMoa2022485",
    local_pdf_path="/Users/oscaralvarado/Desktop/35.pdf",
    disease_state="M1 CRPC",
    line_of_therapy="Post-next-generation hormonal agent",
    biomarker_scope="Alteraciones HRR trazables a nivel de gen",
    followup_implications="Refuerza que olaparib requiere biomarcador HRR trazable y documentado por gen, con fuente analítica identificable.",
    supports_rule_ids=["m1_crpc.profound_hrr_pathway"],
    applies_to_modules=["m1_crpc"],
    field_implications=["hrr_status", "hrr_gene", "biomarker_source"],
    ui_surfaces=["wizard.sidebar", "wizard.results", "patient_profile"],
)

EMBARK_FDA = citation(
    "embark_fda_2023",
    "FDA approves enzalutamide for non-metastatic castration-sensitive prostate cancer with biochemical recurrence.",
    "FDA EMBARK approval",
    "regulatory_update",
    document_id="fda_enza_bcr_2023",
    evidence_role="supportive_trial",
    license_class="public_web_reference",
    doi_or_url="https://www.fda.gov/drugs/resources-information-approved-drugs/fda-approves-enzalutamide-non-metastatic-castration-sensitive-prostate-cancer-biochemical-recurrence",
    disease_state="Biochemical recurrence",
    line_of_therapy="High-risk BCR",
    followup_implications="Restringe la vía con enzalutamida a patrones high-risk BCR documentados y sin opción local curativa predominante.",
    supports_rule_ids=["recurrence_bcr.embark_gating"],
    applies_to_modules=["recurrence_bcr"],
    field_implications=["conventional_imaging_m0", "salvage_local_feasible", "psadt_months"],
    ui_surfaces=["wizard.sidebar", "wizard.results", "patient_profile"],
)

PSMAFORE_REGULATORY = citation(
    "psmafore_regulatory_2025",
    "Pluvicto approved by FDA for expanded indication in earlier use for PSMA-positive metastatic castration-resistant prostate cancer.",
    "Pluvicto earlier-line FDA expansion",
    "regulatory_update",
    document_id="fda_pluvicto_earlier_2025",
    evidence_role="supportive_trial",
    license_class="public_web_reference",
    doi_or_url="https://www.novartis.com/us-en/news/media-releases/pluvicto-approved-fda-expanded-indication-earlier-use-psma-positive-metastatic-castration-resistant-prostate-cancer",
    disease_state="M1 CRPC",
    line_of_therapy="Pre-taxane PSMA-positive disease",
    biomarker_scope="PSMA-positive disease without dominant PSMA-negative lesions",
    followup_implications="Permite abrir una rama pre-taxano conservadora para lutecio-177 PSMA-617 cuando se documenta necesidad clínica de diferir o evitar docetaxel.",
    supports_rule_ids=["m1_crpc.psmafore_pre_taxane"],
    applies_to_modules=["m1_crpc"],
    field_implications=["psma_positive", "psma_negative_dominant_lesions", "docetaxel_fit", "chemotherapy_delay_candidate", "mcrpc_line_context"],
    ui_surfaces=["wizard.sidebar", "wizard.results", "patient_profile"],
)

TALAPRO2_REGULATORY = citation(
    "talapro2_regulatory_2025",
    "Pfizer provides update on U.S. regulatory review for TALZENNA in combination with XTANDI.",
    "Pfizer TALAPRO-2 regulatory update",
    "regulatory_update",
    document_id="pfizer_talapro2_2025",
    evidence_role="supportive_trial",
    license_class="public_web_reference",
    doi_or_url="https://www.pfizer.com/news/announcements/pfizer-provides-update-us-regulatory-review-talzenna-combination-xtandi-broader",
    disease_state="M1 CRPC",
    line_of_therapy="First line",
    biomarker_scope="HRR-mutated disease",
    followup_implications="Mantiene un uso conservador de talazoparib más enzalutamida restringido a mCRPC HRR-mutado.",
    supports_rule_ids=["m1_crpc.talapro2_first_line_hrr"],
    applies_to_modules=["m1_crpc"],
    field_implications=["hrr_status", "hrr_gene", "mcrpc_line_context", "molecular_report_date"],
    ui_surfaces=["wizard.sidebar", "wizard.results"],
)

AKEEGA_MHSPC = citation(
    "akeega_brca2_mcspc_2025",
    "U.S. FDA approves AKEEGA as the first precision therapy for BRCA2-mutated metastatic castration-sensitive prostate cancer.",
    "J&J AKEEGA BRCA2 mCSPC",
    "regulatory_update",
    document_id="jnj_akeega_mcspc_2025",
    evidence_role="supportive_trial",
    license_class="public_web_reference",
    doi_or_url="https://www.jnj.com/media-center/press-releases/u-s-fda-approves-akeega-as-the-first-precision-therapy-for-brca2-mutated-metastatic-castration-sensitive-prostate-cancer-with-54-reduction-in-disease-progression-vs-standard-of-care",
    disease_state="mHSPC",
    line_of_therapy="Frontline precision therapy",
    biomarker_scope="BRCA2-mutated disease",
    followup_implications="Activa una ruta de precisión en mHSPC solo cuando BRCA2, fuente y fecha del ensayo molecular son trazables.",
    supports_rule_ids=["mcspc.akeega_brca2_precision"],
    applies_to_modules=["mcspc_oligo_metachronous", "mcspc_low_volume_sync_oligo", "mcspc_high_volume_sync", "mcspc_high_volume_metachronous", "mcspc_high_volume"],
    field_implications=["brca2_status", "hrr_gene", "molecular_assay_source", "molecular_assay_date"],
    ui_surfaces=["wizard.sidebar", "wizard.results", "patient_profile"],
)

REZVILUTAMIDE_CHART = citation(
    "rezvilutamide_chart_2024",
    "Addition of rezvilutamide to androgen-deprivation therapy in patients with high-volume metastatic hormone-sensitive prostate cancer (CHART).",
    "CHART",
    "supporting_study",
    document_id="chart_rezvilutamide_2024",
    evidence_role="supportive_trial",
    license_class="public_web_reference",
    doi_or_url="https://pubmed.ncbi.nlm.nih.gov/39269783/",
    disease_state="mHSPC",
    line_of_therapy="Frontline doublet",
    followup_implications="Permite visibilizar rezvilutamida como opción hormonal soportada por EAU 2026 sin desplazar la jerarquía primaria de NCCN.",
    supports_rule_ids=["mcspc.rezvilutamide_option"],
    applies_to_modules=["mcspc_oligo_metachronous", "mcspc_low_volume_sync_oligo", "mcspc_high_volume_sync", "mcspc_high_volume_metachronous", "mcspc_high_volume"],
    field_implications=["comorbidity_seizure", "frailty_status", "metastasis_site"],
    ui_surfaces=["wizard.results", "patient_profile"],
)

APCCC_2024 = citation(
    "apccc_2024_advanced_pc",
    "Management of Patients with Advanced Prostate Cancer. Report from the 2024 Advanced Prostate Cancer Consensus Conference (APCCC).",
    "APCCC 2024",
    "consensus_support",
    document_id="doc_36_apccc",
    evidence_role="consensus",
    license_class="publisher_pdf",
    local_pdf_path="/Users/oscaralvarado/Desktop/36.pdf",
    disease_state="Advanced disease",
    followup_implications="Añade una capa de consenso para zonas grises de secuenciación y selección, pero no reemplaza la recomendación primaria basada en guías.",
    supports_rule_ids=["advanced.supportive_consensus_overlay"],
    applies_to_modules=[
        "mcspc_oligo_metachronous",
        "mcspc_low_volume_sync_oligo",
        "mcspc_high_volume",
        "m0_crpc",
        "m1_crpc",
    ],
    field_implications=["frailty_status", "cv_risk_documented", "drug_interaction_reviewed"],
    ui_surfaces=["wizard.results", "patient_profile"],
)

ARSI_CV_META = citation(
    "arsi_cv_meta_2024",
    "Cardiovascular Events and Androgen Receptor Signaling Inhibitors in Advanced Prostate Cancer: A Systematic Review and Meta-Analysis.",
    "ARSI CV meta-analysis",
    "safety_signal",
    document_id="doc_37_arsi_cv_meta",
    evidence_role="safety_signal",
    license_class="publisher_pdf",
    local_pdf_path="/Users/oscaralvarado/Desktop/37.pdf",
    disease_state="Advanced prostate cancer",
    toxicity_scope="Riesgo cardiovascular asociado a ARPI",
    followup_implications="Activa evaluación cardiovascular basal y seguimiento serial cuando se plantea intensificación con ARPI.",
    supports_rule_ids=["advanced.cardio_oncology_overlay"],
    applies_to_modules=[
        "mcspc_oligo_metachronous",
        "mcspc_low_volume_sync_oligo",
        "mcspc_high_volume",
        "m0_crpc",
        "m1_crpc",
    ],
    field_implications=["cv_risk_documented", "baseline_qol", "drug_interaction_reviewed"],
    ui_surfaces=["wizard.results", "patient_profile", "dashboard"],
)

FRAILTY_COMORBIDITY = citation(
    "frailty_comorbidity_2025",
    "Association between frailty and specific comorbidities on oncological outcomes in metastatic hormone-sensitive and castration resistant prostate cancer.",
    "Frailty and comorbidity outcomes",
    "supporting_study",
    document_id="doc_39_frailty",
    evidence_role="supportive_trial",
    license_class="publisher_pdf",
    local_pdf_path="/Users/oscaralvarado/Desktop/39.pdf",
    disease_state="mHSPC and mCRPC",
    followup_implications="Refuerza la necesidad de documentar fragilidad y comorbilidades específicas antes de escalar intensidad terapéutica.",
    supports_rule_ids=["advanced.frailty_geriatric_overlay"],
    applies_to_modules=[
        "mcspc_oligo_metachronous",
        "mcspc_low_volume_sync_oligo",
        "mcspc_high_volume",
        "m0_crpc",
        "m1_crpc",
    ],
    field_implications=["frailty_status", "baseline_qol", "ecog_score"],
    ui_surfaces=["wizard.results", "patient_profile", "dashboard"],
)

ARPI_DDI_REVIEW = citation(
    "arpi_ddi_2024",
    "Androgen receptor pathway inhibitors and drug-drug interactions in prostate cancer.",
    "ARPI DDI review",
    "supporting_study",
    document_id="doc_40_arpi_ddi",
    evidence_role="safety_signal",
    license_class="publisher_pdf",
    local_pdf_path="/Users/oscaralvarado/Desktop/40.pdf",
    disease_state="Advanced prostate cancer",
    toxicity_scope="Interacciones farmacológicas por CYP y polifarmacia",
    followup_implications="Añade revisión estructurada de interacciones farmacológicas antes de iniciar ARPI, especialmente con polifarmacia y fragilidad.",
    supports_rule_ids=["advanced.drug_interaction_review"],
    applies_to_modules=[
        "mcspc_oligo_metachronous",
        "mcspc_low_volume_sync_oligo",
        "mcspc_high_volume",
        "m0_crpc",
        "m1_crpc",
    ],
    field_implications=["drug_interaction_reviewed", "current_medications", "cv_risk_documented"],
    ui_surfaces=["wizard.results", "patient_profile", "dashboard"],
)

ABIRATERONE_DILI = citation(
    "abiraterone_dili_2025",
    "Drug-Induced Liver Injury Caused by Abiraterone Acetate in Patients With Prostate Cancer.",
    "Abiraterone DILI",
    "safety_signal",
    document_id="doc_41_abiraterone_dili",
    evidence_role="safety_signal",
    license_class="open_access_pdf",
    doi_or_url="https://doi.org/10.7759/cureus.83494",
    local_pdf_path="/Users/oscaralvarado/Desktop/41.pdf",
    disease_state="mHSPC and mCRPC",
    toxicity_scope="Hepatotoxicidad por abiraterona",
    followup_implications="Dispara bundle de monitoreo hepático basal y en semanas 4 a 8 cuando se considera o usa abiraterona.",
    supports_rule_ids=["advanced.hepatic_monitoring_bundle"],
    applies_to_modules=[
        "mcspc_oligo_metachronous",
        "mcspc_low_volume_sync_oligo",
        "mcspc_high_volume",
        "m1_crpc",
    ],
    field_implications=["child_pugh_score", "hepatic_risk_factors", "baseline_lft_documented"],
    ui_surfaces=["wizard.results", "patient_profile", "dashboard"],
)

MHSPC_REAL_WORLD = citation(
    "mhspc_real_world_2025",
    "Real-World Evidence of Combination Therapy Use in Metastatic Hormone-Sensitive Prostate Cancer in the United States From 2017 to 2023.",
    "Real-world mHSPC combinations",
    "benchmarking_study",
    document_id="doc_42_mhspc_real_world",
    evidence_role="real_world",
    license_class="publisher_pdf",
    doi_or_url="https://doi.org/10.1200/OP-24-00690",
    local_pdf_path="/Users/oscaralvarado/Desktop/42.pdf",
    disease_state="mHSPC",
    followup_implications="Se usa para benchmarking de adopción de dobletes y tripletes, no para desplazar la jerarquía terapéutica primaria.",
    supports_rule_ids=["mcspc.benchmark_adoption"],
    applies_to_modules=[
        "mcspc_oligo_metachronous",
        "mcspc_low_volume_sync_oligo",
        "mcspc_high_volume",
    ],
    field_implications=["combination_adherence", "baseline_qol", "biomarker_completion"],
    ui_surfaces=["wizard.results", "patient_profile", "dashboard"],
)

MSK_PREOP_NOMOGRAM = citation(
    "msk_preop_nomogram",
    "MSK pre-radical prostatectomy nomogram.",
    "MSK nomogram",
    "benchmark_reference",
    document_id="benchmark_msk_preop",
    evidence_role="benchmark",
    license_class="public_web_reference",
    doi_or_url="https://www.mskcc.org/nomograms/prostate/pre_op",
    disease_state="Localized initial",
    followup_implications="Sirve como benchmark de producto para variables preoperatorias y refinamiento de riesgo, sin actuar como motor normativo.",
    supports_rule_ids=["localized_initial.product_benchmark"],
    applies_to_modules=["localized_initial"],
    field_implications=["clinical_tstage", "psa", "gleason_primary", "gleason_secondary"],
    ui_surfaces=["wizard.sidebar", "dashboard"],
)

CANARY_PASS = citation(
    "canary_pass",
    "Canary PASS active surveillance program.",
    "Canary PASS",
    "benchmark_reference",
    document_id="benchmark_canary_pass",
    evidence_role="benchmark",
    license_class="public_web_reference",
    doi_or_url="https://canarypass.org/",
    disease_state="Active surveillance",
    followup_implications="Sirve como benchmark de producto para seguimiento estructurado y confirmatory biopsy en vigilancia activa.",
    supports_rule_ids=["localized_initial.active_surveillance_benchmark"],
    applies_to_modules=["localized_initial", "post_negative_biopsy_followup"],
    field_implications=["confirmatory_biopsy_planned", "baseline_qol", "psa_kinetics"],
    ui_surfaces=["wizard.sidebar", "dashboard"],
)

ERSPC_RISK_CALCULATOR = citation(
    "erspc_risk_calculator",
    "European Randomized Study of Screening for Prostate Cancer (ERSPC) Risk Calculator.",
    "ERSPC Risk Calculator",
    "benchmark_reference",
    document_id="benchmark_erspc",
    evidence_role="benchmark",
    license_class="public_web_reference",
    doi_or_url="https://www.prostatecancer-riskcalculator.com/",
    disease_state="Deteccion temprana y rebiopsia",
    followup_implications="Permite refinar umbral diagnostico y de rebiopsia junto con MRI, PSAD y antecedentes, sin sustituir la recomendacion primaria de guias.",
    supports_rule_ids=["diagnostic_workup.erspc_support", "post_negative_biopsy_followup.erspc_support"],
    applies_to_modules=["diagnostic_workup", "post_negative_biopsy_followup"],
    field_implications=["age", "psa", "dre_suspicious", "prior_biopsy_count", "prostate_volume_ml"],
    ui_surfaces=["wizard.sidebar", "wizard.results", "dashboard"],
)

PREDICT_PROSTATE = citation(
    "predict_prostate",
    "PREDICT Prostate survival model.",
    "PREDICT Prostate",
    "benchmark_reference",
    document_id="benchmark_predict_prostate",
    evidence_role="benchmark",
    license_class="public_web_reference",
    doi_or_url="https://prostate.predict.nhs.uk/",
    disease_state="Localized initial",
    followup_implications="Ayuda a cuantificar beneficio absoluto y apoyar decision compartida en enfermedad localizada, sin desplazar NCCN/EAU.",
    supports_rule_ids=["localized_initial.predict_support"],
    applies_to_modules=["localized_initial"],
    field_implications=["age", "psa", "clinical_tstage", "isup_grade", "life_expectancy_years"],
    ui_surfaces=["wizard.sidebar", "wizard.results", "patient_profile"],
)

PARTIN_TABLES = citation(
    "partin_tables",
    "Updated Partin Tables for the prediction of final pathological stage.",
    "Partin Tables",
    "benchmark_reference",
    document_id="benchmark_partin",
    evidence_role="benchmark",
    license_class="public_web_reference",
    doi_or_url="https://pubmed.ncbi.nlm.nih.gov/28318271/",
    disease_state="Localized initial",
    followup_implications="Ayuda a counseling patologico preoperatorio y riesgo ganglionar, sin sustituir la jerarquia de guias.",
    supports_rule_ids=["localized_initial.partin_support"],
    applies_to_modules=["localized_initial"],
    field_implications=["clinical_tstage", "psa", "isup_grade"],
    ui_surfaces=["wizard.sidebar", "wizard.results", "patient_profile"],
)

CAPRA_UCSF = citation(
    "capra_ucsf",
    "Cancer of the Prostate Risk Assessment (CAPRA) and CAPRA-S.",
    "CAPRA / CAPRA-S",
    "benchmark_reference",
    document_id="benchmark_capra",
    evidence_role="benchmark",
    license_class="public_web_reference",
    doi_or_url="https://urology.ucsf.edu/research/cancer/prostate-cancer-risk-assessment-and-the-ucla-prostate-cancer-index",
    disease_state="Localized and post-prostatectomy",
    followup_implications="Permite refinar riesgo preoperatorio y posoperatorio como capa de apoyo compatible con NCCN/EAU.",
    supports_rule_ids=["localized_initial.capra_support", "post_prostatectomy.capra_s_support"],
    applies_to_modules=["localized_initial", "post_prostatectomy", "recurrence_bcr"],
    field_implications=["psa", "clinical_tstage", "isup_grade", "pathologic_stage"],
    ui_surfaces=["wizard.sidebar", "wizard.results", "patient_profile"],
)

CRPC_PUBLIC_DEFINITION = citation(
    "nci_crpc_definition",
    "Castrate-resistant prostate cancer definition.",
    "NCI definition",
    "supporting_study",
    evidence_role="supportive_trial",
    license_class="public_web_reference",
    doi_or_url="https://www.cancer.gov/publications/dictionaries/cancer-terms/def/castrate-resistant-prostate-cancer",
    disease_state="CRPC verification",
    followup_implications="Refuerza que la enfermedad resistente a la castración exige progresión con testosterona en rango de castración.",
    supports_rule_ids=["adt_progression_verification.crpc_definition_support"],
    applies_to_modules=["adt_progression_verification"],
    field_implications=["castrate_testosterone_status", "testosterone_value", "progression_pattern"],
    ui_surfaces=["wizard.sidebar", "wizard.results"],
)

FDA_APALUTAMIDE_NMCRPC = citation(
    "fda_apalutamide_nmcrpc",
    "FDA approves apalutamide for non-metastatic castration-resistant prostate cancer.",
    "FDA apalutamide nmCRPC",
    "supporting_study",
    evidence_role="supportive_trial",
    license_class="public_web_reference",
    doi_or_url="https://www.fda.gov/drugs/resources-information-approved-drugs/fda-approves-apalutamide-non-metastatic-castration-resistant-prostate-cancer",
    disease_state="M0 CRPC",
    followup_implications="Aporta soporte regulatorio para el carril nmCRPC una vez confirmadas castración e imagen convencional M0.",
    supports_rule_ids=["adt_progression_verification.nmcrpc_redirection"],
    applies_to_modules=["adt_progression_verification", "m0_crpc"],
    field_implications=["psadt_months", "castrate_testosterone_status", "conventional_imaging_status"],
    ui_surfaces=["wizard.sidebar", "wizard.results"],
)

DOCUMENTS = _document_registry(
    NCCN_PRIMARY,
    EAU_PRIMARY,
    ACTIVE_SURVEILLANCE_REAL_WORLD,
    BENIGN_BIOPSY_LONG_TERM,
    LATE_RT_TOXICITY,
    PROPEL_SYMPTOMATIC,
    CARD_TRIAL,
    VISION_TRIAL,
    PROFOUND_TRIAL,
    EMBARK_FDA,
    PSMAFORE_REGULATORY,
    TALAPRO2_REGULATORY,
    AKEEGA_MHSPC,
    REZVILUTAMIDE_CHART,
    APCCC_2024,
    ARSI_CV_META,
    FRAILTY_COMORBIDITY,
    ARPI_DDI_REVIEW,
    ABIRATERONE_DILI,
    MHSPC_REAL_WORLD,
    MSK_PREOP_NOMOGRAM,
    CANARY_PASS,
    ERSPC_RISK_CALCULATOR,
    PREDICT_PROSTATE,
    PARTIN_TABLES,
    CAPRA_UCSF,
)

MODULES = {
    "diagnostic_workup": ModuleEvidence(
        module="diagnostic_workup",
        title="Estudio diagnóstico antes de confirmar cáncer de próstata",
        nccn_panels=["PROS-A", "PROS-B"],
        eau_sections=["Diagnostic evaluation", "Risk-adapted early detection"],
        pivotal_trials=[],
        core_questions=[
            "¿La sospecha de cáncer clínicamente significativo justifica resonancia magnética multiparamétrica, biopsia dirigida y biopsia sistemática?",
            "¿Existe un patrón de sospecha suficientemente alto como para planear imagen avanzada tras confirmación histológica?",
        ],
        source_citations=[NCCN_PRIMARY, EAU_PRIMARY, ERSPC_RISK_CALCULATOR],
    ),
    "post_negative_biopsy_followup": ModuleEvidence(
        module="post_negative_biopsy_followup",
        title="Seguimiento después de una biopsia benigna inicial",
        nccn_panels=["PROS-A", "PROS-B"],
        eau_sections=["Follow-up after negative biopsy"],
        pivotal_trials=["Palmstedt 2019"],
        core_questions=[
            "¿El seguimiento puede mantenerse de baja intensidad después de una biopsia benigna inicial?",
            "¿Cuándo debe reabrirse el estudio diagnóstico con resonancia magnética o nueva biopsia?",
        ],
        source_citations=[NCCN_PRIMARY, EAU_PRIMARY, BENIGN_BIOPSY_LONG_TERM, CANARY_PASS, ERSPC_RISK_CALCULATOR],
    ),
    "localized_initial": ModuleEvidence(
        module="localized_initial",
        title="Diagnóstico inicial localizado o regional con ganglios regionales positivos y sin metástasis a distancia",
        nccn_panels=["PROS-1", "PROS-2", "PROS-3", "PROS-4", "PROS-5", "PROS-6", "PROS-7", "PROS-A", "PROS-B", "PROS-F", "PROS-G", "PROS-H"],
        eau_sections=["Classification and staging systems", "Treatment"],
        pivotal_trials=["ProtecT", "SPCG-4", "PIVOT"],
        core_questions=[
            "¿Cuál es el grupo de riesgo exacto según la Red Nacional Integral del Cáncer (NCCN) versión 5.2026?",
            "¿La vigilancia activa está indicada, es preferente o no se recomienda?",
            "¿Qué tratamientos locales son elegibles según riesgo, expectativa de vida e histología?",
        ],
        source_citations=[NCCN_PRIMARY, EAU_PRIMARY, ACTIVE_SURVEILLANCE_REAL_WORLD, LATE_RT_TOXICITY, MSK_PREOP_NOMOGRAM, CANARY_PASS, PARTIN_TABLES, PREDICT_PROSTATE, CAPRA_UCSF],
    ),
    "post_prostatectomy": ModuleEvidence(
        module="post_prostatectomy",
        title="Seguimiento después de prostatectomía radical",
        nccn_panels=["PROS-8", "PROS-9", "PROS-G", "PROS-H"],
        eau_sections=["Treatment", "Follow-up"],
        pivotal_trials=["SWOG-8794", "ARO 96-02", "RADICALS-RT"],
        core_questions=[
            "¿El paciente está en vigilancia, consideración de adyuvancia o escenario de rescate temprano?",
            "¿Cuál es la estimación del puntaje postoperatorio CAPRA-S en el contexto correcto?",
        ],
        source_citations=[NCCN_PRIMARY, EAU_PRIMARY, LATE_RT_TOXICITY, CAPRA_UCSF],
    ),
    "recurrence_bcr": ModuleEvidence(
        module="recurrence_bcr",
        title="Recurrencia bioquímica y segunda recurrencia bioquímica sin metástasis",
        nccn_panels=["PROS-9", "PROS-10", "PROS-11", "PROS-12", "PROS-H"],
        eau_sections=["Treatment", "Biochemical recurrence"],
        pivotal_trials=["RAVES", "GETUG-AFU 16", "RTOG 9601", "EMBARK"],
        core_questions=[
            "¿Se trata de recurrencia posterior a prostatectomía radical, posterior a radioterapia o segunda recurrencia bioquímica?",
            "¿Está indicado el rescate temprano y debe añadirse terapia de privación androgénica?",
        ],
        source_citations=[NCCN_PRIMARY, EAU_PRIMARY, LATE_RT_TOXICITY, EMBARK_FDA, APCCC_2024, CAPRA_UCSF],
    ),
    "adt_progression_verification": ModuleEvidence(
        module="adt_progression_verification",
        title="Progresión bajo ADT / verificación de castración",
        nccn_panels=["PROS-16", "PROS-17", "PROS-M"],
        eau_sections=["Castration-resistant disease", "Follow-up"],
        pivotal_trials=["SPARTAN", "ARAMIS", "PROSPER"],
        core_questions=[
            "¿Existe testosterona en rango de castración confirmada o primero debe optimizarse la supresión androgénica?",
            "¿La imagen convencional define ya un carril M0 o M1 resistente a la castración?",
            "¿La progresión bajo ADT es solo bioquímica o ya existe progresión radiográfica o clínica con castración confirmada?",
        ],
        source_citations=[NCCN_PRIMARY, EAU_PRIMARY, CRPC_PUBLIC_DEFINITION, FDA_APALUTAMIDE_NMCRPC],
    ),
    "mcspc_oligo_metachronous": ModuleEvidence(
        module="mcspc_oligo_metachronous",
        title="Enfermedad metastásica sensible a la castración oligometastásica metacrónica",
        nccn_panels=["PROS-13", "PROS-M", "PROS-N"],
        eau_sections=["Metastatic disease treatment"],
        pivotal_trials=["STAMPEDE", "PEACE-1", "ARASENS"],
        core_questions=[
            "¿Puede considerarse el tratamiento dirigido a metástasis?",
            "¿Qué intensificación sistémica es elegible?",
        ],
        source_citations=[NCCN_PRIMARY, EAU_PRIMARY, AKEEGA_MHSPC, REZVILUTAMIDE_CHART, APCCC_2024, ARSI_CV_META, FRAILTY_COMORBIDITY, ARPI_DDI_REVIEW, ABIRATERONE_DILI, MHSPC_REAL_WORLD],
    ),
    "mcspc_low_volume_sync_oligo": ModuleEvidence(
        module="mcspc_low_volume_sync_oligo",
        title="Enfermedad metastásica sensible a la castración de bajo volumen u oligometastásica sincrónica",
        nccn_panels=["PROS-14", "PROS-M", "PROS-N"],
        eau_sections=["Metastatic disease treatment"],
        pivotal_trials=["STAMPEDE H", "ARCHES", "ENZAMET", "TITAN", "ARANOTE"],
        core_questions=[
            "¿La radioterapia al tumor primario es apropiada?",
            "¿Qué doblete se ajusta mejor a este paciente?",
        ],
        source_citations=[NCCN_PRIMARY, EAU_PRIMARY, AKEEGA_MHSPC, REZVILUTAMIDE_CHART, APCCC_2024, ARSI_CV_META, FRAILTY_COMORBIDITY, ARPI_DDI_REVIEW, ABIRATERONE_DILI, MHSPC_REAL_WORLD],
    ),
    "mcspc_high_volume_sync": ModuleEvidence(
        module="mcspc_high_volume_sync",
        title="Enfermedad metastásica sensible a la castración de alto volumen sincrónica",
        nccn_panels=["PROS-15", "PROS-M", "PROS-N"],
        eau_sections=["Metastatic disease treatment"],
        pivotal_trials=["CHAARTED", "LATITUDE", "ARANOTE", "ARASENS", "PEACE-1"],
        core_questions=[
            "¿El paciente es apto para docetaxel según ECOG, neuropatía, fragilidad y Child-Pugh?",
            "¿Debe priorizarse triplete y qué backbone trial-like corresponde en enfermedad de novo/sincrónica?",
        ],
        source_citations=[NCCN_PRIMARY, EAU_PRIMARY, AKEEGA_MHSPC, REZVILUTAMIDE_CHART, APCCC_2024, ARSI_CV_META, FRAILTY_COMORBIDITY, ARPI_DDI_REVIEW, ABIRATERONE_DILI, MHSPC_REAL_WORLD],
    ),
    "mcspc_high_volume_metachronous": ModuleEvidence(
        module="mcspc_high_volume_metachronous",
        title="Enfermedad metastásica sensible a la castración de alto volumen metacrónica",
        nccn_panels=["PROS-15", "PROS-M", "PROS-N"],
        eau_sections=["Metastatic disease treatment"],
        pivotal_trials=["CHAARTED", "LATITUDE", "ARANOTE", "ARASENS"],
        core_questions=[
            "¿El paciente es apto para docetaxel según ECOG, neuropatía, fragilidad y Child-Pugh?",
            "¿Debe intensificarse con triplete o doblete visible sin sobreextrapolar PEACE-1 como backbone principal?",
        ],
        source_citations=[NCCN_PRIMARY, EAU_PRIMARY, AKEEGA_MHSPC, REZVILUTAMIDE_CHART, APCCC_2024, ARSI_CV_META, FRAILTY_COMORBIDITY, ARPI_DDI_REVIEW, ABIRATERONE_DILI, MHSPC_REAL_WORLD],
    ),
    "mcspc_high_volume": ModuleEvidence(
        module="mcspc_high_volume",
        title="Enfermedad metastásica sensible a la castración de alto volumen",
        nccn_panels=["PROS-15", "PROS-M", "PROS-N"],
        eau_sections=["Metastatic disease treatment"],
        pivotal_trials=["CHAARTED", "LATITUDE", "ARANOTE", "ARASENS", "PEACE-1"],
        core_questions=[
            "¿El paciente es apto para docetaxel?",
            "¿Qué triplete o doblete debe priorizarse?",
        ],
        source_citations=[NCCN_PRIMARY, EAU_PRIMARY, AKEEGA_MHSPC, REZVILUTAMIDE_CHART, APCCC_2024, ARSI_CV_META, FRAILTY_COMORBIDITY, ARPI_DDI_REVIEW, ABIRATERONE_DILI, MHSPC_REAL_WORLD],
    ),
    "m0_crpc": ModuleEvidence(
        module="m0_crpc",
        title="Enfermedad resistente a la castración sin metástasis",
        nccn_panels=["PROS-16", "PROS-M"],
        eau_sections=["Castration-resistant disease"],
        pivotal_trials=["SPARTAN", "PROSPER", "ARAMIS"],
        core_questions=[
            "¿El paciente tiene alto riesgo de enfermedad resistente a la castración sin metástasis según el tiempo de duplicación del antígeno prostático específico?",
            "¿Qué inhibidor del receptor androgénico se ajusta mejor a las contraindicaciones?",
        ],
        source_citations=[NCCN_PRIMARY, EAU_PRIMARY, APCCC_2024, ARSI_CV_META, FRAILTY_COMORBIDITY, ARPI_DDI_REVIEW],
    ),
    "m1_crpc": ModuleEvidence(
        module="m1_crpc",
        title="Enfermedad resistente a la castración con metástasis",
        nccn_panels=["PROS-17", "PROS-18", "PROS-C", "PROS-M"],
        eau_sections=["Castration-resistant disease"],
        pivotal_trials=["PROfound", "VISION", "CARD", "TALAPRO-2", "MAGNITUDE", "PROpel", "KEYNOTE-158"],
        core_questions=[
            "¿Qué clase terapéutica permanece activa después de la exposición previa a inhibidores del receptor androgénico y taxanos?",
            "¿Existen opciones guiadas por biomarcadores?",
        ],
        source_citations=[NCCN_PRIMARY, EAU_PRIMARY, CARD_TRIAL, VISION_TRIAL, PROFOUND_TRIAL, PSMAFORE_REGULATORY, TALAPRO2_REGULATORY, PROPEL_SYMPTOMATIC, APCCC_2024, ARSI_CV_META, FRAILTY_COMORBIDITY, ARPI_DDI_REVIEW, ABIRATERONE_DILI],
    ),
}
