from __future__ import annotations


ARPI_BENEFIT_MATRIX = {
    "m0_crpc": {
        "ADT_DAROLUTAMIDE": {
            "scenario_match": "exact",
            "regulatory_support": "FDA 30-Jul-2019 / ARAMIS",
            "primary_benefit_endpoint": "MFS",
            "os_benefit_strength": "moderate",
            "mfs_benefit_strength": "high",
            "rpfs_benefit_strength": "low",
            "evidence_maturity": "mature",
            "trial_basis": "ARAMIS / FDA nmCRPC 2019",
            "volume_fit": "not_applicable",
            "temporality_fit": "exact",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 14.6,
        },
        "ADT_ENZALUTAMIDE": {
            "scenario_match": "exact",
            "regulatory_support": "FDA 13-Jul-2018 / PROSPER",
            "primary_benefit_endpoint": "MFS",
            "os_benefit_strength": "moderate",
            "mfs_benefit_strength": "high",
            "rpfs_benefit_strength": "low",
            "evidence_maturity": "mature",
            "trial_basis": "PROSPER / FDA nmCRPC 2018",
            "volume_fit": "not_applicable",
            "temporality_fit": "exact",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 14.8,
        },
        "ADT_APALUTAMIDE": {
            "scenario_match": "exact",
            "regulatory_support": "FDA 14-Feb-2018 / SPARTAN",
            "primary_benefit_endpoint": "MFS",
            "os_benefit_strength": "moderate",
            "mfs_benefit_strength": "high",
            "rpfs_benefit_strength": "low",
            "evidence_maturity": "mature",
            "trial_basis": "SPARTAN / FDA nmCRPC 2018",
            "volume_fit": "not_applicable",
            "temporality_fit": "exact",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 14.4,
        },
    },
    "mcspc_high_volume_sync": {
        "ADT_DOCETAXEL_DAROLUTAMIDE": {
            "scenario_match": "exact",
            "regulatory_support": "FDA 03-Jun-2025 / ARASENS + darolutamide mCSPC label extension",
            "primary_benefit_endpoint": "OS",
            "os_benefit_strength": "high",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "high",
            "evidence_maturity": "mature",
            "trial_basis": "ARASENS / FDA mCSPC 2025",
            "volume_fit": "exact",
            "temporality_fit": "exact",
            "triplet_fit": "exact",
            "doublet_fit": "not_applicable",
            "benefit_score": 21.5,
        },
        "ADT_DOCETAXEL_ABIRATERONE": {
            "scenario_match": "exact",
            "regulatory_support": "PEACE-1 / EAU 2026",
            "primary_benefit_endpoint": "OS",
            "os_benefit_strength": "high",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "high",
            "evidence_maturity": "mature",
            "trial_basis": "PEACE-1",
            "volume_fit": "exact",
            "temporality_fit": "exact",
            "triplet_fit": "exact",
            "doublet_fit": "not_applicable",
            "benefit_score": 21.1,
        },
        "ADT_ABIRATERONE": {
            "scenario_match": "supported_extrapolation",
            "regulatory_support": "FDA 2018 / LATITUDE + STAMPEDE high-risk de novo",
            "primary_benefit_endpoint": "OS",
            "os_benefit_strength": "high",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "moderate",
            "evidence_maturity": "mature",
            "trial_basis": "LATITUDE / STAMPEDE",
            "volume_fit": "supported_extrapolation",
            "temporality_fit": "exact",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 17.4,
        },
        "ADT_DAROLUTAMIDE": {
            "scenario_match": "exact",
            "regulatory_support": "FDA 03-Jun-2025 / ARANOTE + label expansion",
            "primary_benefit_endpoint": "rPFS",
            "os_benefit_strength": "moderate",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "high",
            "evidence_maturity": "intermediate",
            "trial_basis": "ARANOTE / FDA mCSPC 2025",
            "volume_fit": "exact",
            "temporality_fit": "exact",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 16.6,
        },
        "ADT_ENZALUTAMIDE": {
            "scenario_match": "exact",
            "regulatory_support": "FDA 16-Dec-2019 / ARCHES ENZAMET",
            "primary_benefit_endpoint": "OS",
            "os_benefit_strength": "high",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "moderate",
            "evidence_maturity": "mature",
            "trial_basis": "ARCHES / ENZAMET / FDA mCSPC 2019",
            "volume_fit": "exact",
            "temporality_fit": "exact",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 17.0,
        },
        "ADT_APALUTAMIDE": {
            "scenario_match": "exact",
            "regulatory_support": "FDA 17-Sep-2019 / TITAN",
            "primary_benefit_endpoint": "OS",
            "os_benefit_strength": "high",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "moderate",
            "evidence_maturity": "mature",
            "trial_basis": "TITAN / FDA mCSPC 2019",
            "volume_fit": "exact",
            "temporality_fit": "exact",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 16.8,
        },
    },
    "mcspc_high_volume_metachronous": {
        "ADT_DOCETAXEL_DAROLUTAMIDE": {
            "scenario_match": "supported_extrapolation",
            "regulatory_support": "FDA 03-Jun-2025 / ARASENS extrapolation",
            "primary_benefit_endpoint": "OS",
            "os_benefit_strength": "high",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "high",
            "evidence_maturity": "intermediate",
            "trial_basis": "ARASENS extrapolado a alto volumen metacrónico",
            "volume_fit": "exact",
            "temporality_fit": "supported_extrapolation",
            "triplet_fit": "supported_extrapolation",
            "doublet_fit": "not_applicable",
            "benefit_score": 18.5,
        },
        "ADT_DOCETAXEL_ABIRATERONE": {
            "scenario_match": "weak_extrapolation",
            "regulatory_support": "PEACE-1",
            "primary_benefit_endpoint": "OS",
            "os_benefit_strength": "high",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "high",
            "evidence_maturity": "intermediate",
            "trial_basis": "PEACE-1 con extrapolación fuera del de novo/sincrónico",
            "volume_fit": "exact",
            "temporality_fit": "weak_extrapolation",
            "triplet_fit": "supported_extrapolation",
            "doublet_fit": "not_applicable",
            "benefit_score": 15.2,
        },
        "ADT_ABIRATERONE": {
            "scenario_match": "supported_extrapolation",
            "regulatory_support": "LATITUDE / STAMPEDE",
            "primary_benefit_endpoint": "OS",
            "os_benefit_strength": "high",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "moderate",
            "evidence_maturity": "mature",
            "trial_basis": "LATITUDE / STAMPEDE con extrapolación a metacrónico",
            "volume_fit": "supported_extrapolation",
            "temporality_fit": "supported_extrapolation",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 15.6,
        },
        "ADT_DAROLUTAMIDE": {
            "scenario_match": "exact",
            "regulatory_support": "FDA 03-Jun-2025 / ARANOTE",
            "primary_benefit_endpoint": "rPFS",
            "os_benefit_strength": "moderate",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "high",
            "evidence_maturity": "intermediate",
            "trial_basis": "ARANOTE / label expansion",
            "volume_fit": "exact",
            "temporality_fit": "exact",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 16.2,
        },
        "ADT_ENZALUTAMIDE": {
            "scenario_match": "exact",
            "regulatory_support": "FDA 16-Dec-2019 / ARCHES ENZAMET",
            "primary_benefit_endpoint": "OS",
            "os_benefit_strength": "high",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "moderate",
            "evidence_maturity": "mature",
            "trial_basis": "ARCHES / ENZAMET",
            "volume_fit": "exact",
            "temporality_fit": "exact",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 16.7,
        },
        "ADT_APALUTAMIDE": {
            "scenario_match": "exact",
            "regulatory_support": "FDA 17-Sep-2019 / TITAN",
            "primary_benefit_endpoint": "OS",
            "os_benefit_strength": "high",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "moderate",
            "evidence_maturity": "mature",
            "trial_basis": "TITAN",
            "volume_fit": "exact",
            "temporality_fit": "exact",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 16.5,
        },
    },
    "mcspc_low_volume_sync_oligo": {
        "ADT_DAROLUTAMIDE": {
            "scenario_match": "exact",
            "regulatory_support": "FDA 03-Jun-2025 / ARANOTE",
            "primary_benefit_endpoint": "rPFS",
            "os_benefit_strength": "moderate",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "high",
            "evidence_maturity": "intermediate",
            "trial_basis": "ARANOTE / label expansion",
            "volume_fit": "exact",
            "temporality_fit": "exact",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 15.6,
        },
        "ADT_ENZALUTAMIDE": {
            "scenario_match": "exact",
            "regulatory_support": "FDA 16-Dec-2019 / ARCHES ENZAMET",
            "primary_benefit_endpoint": "OS",
            "os_benefit_strength": "high",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "moderate",
            "evidence_maturity": "mature",
            "trial_basis": "ARCHES / ENZAMET",
            "volume_fit": "exact",
            "temporality_fit": "exact",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 16.0,
        },
        "ADT_APALUTAMIDE": {
            "scenario_match": "exact",
            "regulatory_support": "FDA 17-Sep-2019 / TITAN",
            "primary_benefit_endpoint": "OS",
            "os_benefit_strength": "high",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "moderate",
            "evidence_maturity": "mature",
            "trial_basis": "TITAN",
            "volume_fit": "exact",
            "temporality_fit": "exact",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 15.8,
        },
        "ADT_ABIRATERONE": {
            "scenario_match": "supported_extrapolation",
            "regulatory_support": "LATITUDE / STAMPEDE",
            "primary_benefit_endpoint": "OS",
            "os_benefit_strength": "moderate",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "moderate",
            "evidence_maturity": "mature",
            "trial_basis": "LATITUDE / STAMPEDE con extrapolación a bajo volumen",
            "volume_fit": "supported_extrapolation",
            "temporality_fit": "exact",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 14.6,
        },
    },
    "mcspc_oligo_metachronous": {
        "ADT_DAROLUTAMIDE": {
            "scenario_match": "exact",
            "regulatory_support": "FDA 03-Jun-2025 / ARANOTE",
            "primary_benefit_endpoint": "rPFS",
            "os_benefit_strength": "moderate",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "high",
            "evidence_maturity": "intermediate",
            "trial_basis": "ARANOTE / label expansion",
            "volume_fit": "exact",
            "temporality_fit": "exact",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 15.3,
        },
        "ADT_ENZALUTAMIDE": {
            "scenario_match": "exact",
            "regulatory_support": "FDA 16-Dec-2019 / ARCHES ENZAMET",
            "primary_benefit_endpoint": "OS",
            "os_benefit_strength": "high",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "moderate",
            "evidence_maturity": "mature",
            "trial_basis": "ARCHES / ENZAMET",
            "volume_fit": "exact",
            "temporality_fit": "exact",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 15.7,
        },
        "ADT_APALUTAMIDE": {
            "scenario_match": "exact",
            "regulatory_support": "FDA 17-Sep-2019 / TITAN",
            "primary_benefit_endpoint": "OS",
            "os_benefit_strength": "high",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "moderate",
            "evidence_maturity": "mature",
            "trial_basis": "TITAN",
            "volume_fit": "exact",
            "temporality_fit": "exact",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 15.5,
        },
        "ADT_ABIRATERONE": {
            "scenario_match": "supported_extrapolation",
            "regulatory_support": "LATITUDE / STAMPEDE",
            "primary_benefit_endpoint": "OS",
            "os_benefit_strength": "moderate",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "moderate",
            "evidence_maturity": "mature",
            "trial_basis": "LATITUDE / STAMPEDE con extrapolación a oligometastásico metacrónico",
            "volume_fit": "supported_extrapolation",
            "temporality_fit": "supported_extrapolation",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 14.1,
        },
    },
    "m1_crpc": {
        "ADT_ENZALUTAMIDE": {
            "scenario_match": "exact",
            "regulatory_support": "FDA mCRPC / PREVAIL + AFFIRM",
            "primary_benefit_endpoint": "OS",
            "os_benefit_strength": "high",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "high",
            "evidence_maturity": "mature",
            "trial_basis": "PREVAIL / AFFIRM",
            "volume_fit": "not_applicable",
            "temporality_fit": "exact",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 16.0,
        },
        "ADT_ABIRATERONE": {
            "scenario_match": "exact",
            "regulatory_support": "FDA mCRPC / COU-AA-302",
            "primary_benefit_endpoint": "OS",
            "os_benefit_strength": "high",
            "mfs_benefit_strength": "low",
            "rpfs_benefit_strength": "high",
            "evidence_maturity": "mature",
            "trial_basis": "COU-AA-302",
            "volume_fit": "not_applicable",
            "temporality_fit": "exact",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 15.8,
        },
    },
    "recurrence_bcr": {
        "ADT_ENZALUTAMIDE": {
            "scenario_match": "exact",
            "regulatory_support": "FDA 16-Nov-2023 / EMBARK",
            "primary_benefit_endpoint": "MFS",
            "os_benefit_strength": "low",
            "mfs_benefit_strength": "high",
            "rpfs_benefit_strength": "low",
            "evidence_maturity": "intermediate",
            "trial_basis": "EMBARK / FDA high-risk BCR 2023",
            "volume_fit": "not_applicable",
            "temporality_fit": "exact",
            "triplet_fit": "not_applicable",
            "doublet_fit": "exact",
            "benefit_score": 13.8,
        },
    },
}


def benefit_profile_for_state(state: str, regimen_code: str) -> dict[str, object]:
    return dict(ARPI_BENEFIT_MATRIX.get(str(state or "").strip(), {}).get(str(regimen_code or "").strip(), {}))
