from __future__ import annotations

from prostanet.shared.contracts import FieldSpec, module_schema


STATE_CLASSIFIER_SCHEMA = module_schema(
    "state_classifier",
    "Clasificador de estado clínico",
    "Determina el módulo adecuado antes de emitir recomendaciones terapéuticas y evita mezclar pacientes diagnósticos, localizados, recurrentes y avanzados.",
    fields=[
        FieldSpec(
            "known_cancer_diagnosis",
            "Diagnóstico confirmado de cáncer de próstata",
            "select",
            options=["1", "0"],
            default="1",
            group="Contexto diagnóstico",
            group_order=1,
            clinical_role="required",
            evidence_tags=["nccn_primary", "classifier"],
            benchmark_note="Evita enrutar a rutas terapéuticas cuando aún no existe confirmación histológica.",
        ),
        FieldSpec(
            "prior_negative_biopsy",
            "Biopsia prostática previa benigna",
            "select",
            options=["0", "1"],
            default="0",
            group="Contexto diagnóstico",
            group_order=1,
            clinical_role="required",
            evidence_tags=["negative_biopsy_followup"],
        ),
        FieldSpec(
            "prior_prostatectomy",
            "Prostatectomía radical previa",
            "select",
            options=["0", "1"],
            default="0",
            group="Tratamiento local previo",
            group_order=2,
            clinical_role="required",
            evidence_tags=["recurrence_pathway"],
        ),
        FieldSpec(
            "prior_radiation",
            "Radioterapia previa",
            "select",
            options=["0", "1"],
            default="0",
            group="Tratamiento local previo",
            group_order=2,
            clinical_role="required",
            evidence_tags=["recurrence_pathway"],
        ),
        FieldSpec(
            "bcr2",
            "Segunda recurrencia bioquímica",
            "select",
            options=["0", "1"],
            default="0",
            group="Recurrencia bioquímica",
            group_order=3,
            clinical_role="decision_refiner",
            evidence_tags=["bcr2_pathway"],
            benchmark_note="Solo debe activarse si ya se confirmó la elegibilidad exacta del escenario BCR2 N0M0.",
        ),
        FieldSpec(
            "metastasis_site",
            "Sitio de metástasis",
            "select",
            help_text="Use M0 si no se conoce enfermedad metastásica a distancia.",
            options=["M0", "Bone", "Node", "Visceral", "Oligometastatic"],
            default="M0",
            group="Carga metastásica",
            group_order=4,
            clinical_role="required",
            evidence_tags=["staging"],
        ),
        FieldSpec(
            "metastasis_count",
            "Número de metástasis",
            "number",
            default=0,
            group="Carga metastásica",
            group_order=4,
            clinical_role="decision_refiner",
            unit="lesiones",
            evidence_tags=["staging", "chaarted"],
        ),
        FieldSpec(
            "volume_disease",
            "Volumen de enfermedad",
            "select",
            options=["Low", "High"],
            default="Low",
            group="Carga metastásica",
            group_order=4,
            clinical_role="decision_refiner",
            evidence_tags=["chaarted"],
        ),
        FieldSpec(
            "metachronous_metastasis",
            "Metástasis metacrónicas",
            "select",
            options=["0", "1"],
            default="0",
            group="Carga metastásica",
            group_order=4,
            clinical_role="required",
            evidence_tags=["metachronous"],
            benchmark_note="Diferencia de novo frente a metacrónico para no mezclar flujos de mCSPC.",
        ),
        FieldSpec(
            "castration_resistant",
            "Estado resistente a la castración",
            "select",
            options=["0", "1"],
            default="0",
            group="Estado sistémico",
            group_order=5,
            clinical_role="required",
            evidence_tags=["crpc"],
        ),
    ],
)
