from __future__ import annotations

from prostanet.shared.contracts import FieldSpec, module_schema


MCSPC_LOW_VOLUME_SCHEMA = module_schema(
    "mcspc_low_volume_sync_oligo",
    "mCSPC bajo volumen o oligometastásico sincrónico",
    "Ruta de dobletes, tripletes seleccionados y radioterapia al primario para enfermedad metastásica sensible a la castración de bajo volumen.",
    fields=[
        FieldSpec(
            "metastatic_components_capture",
            "Distribución metastásica documentada",
            "metastatic_components",
            required=True,
            group="Carga metastásica",
            group_order=1,
            clinical_role="required",
            help_text="Capture hueso, víscera y ganglios no regionales como componentes coexistentes cuando corresponda. El volumen se deriva por backend desde esta distribución.",
            benchmark_note="Evita pedir un sitio metastásico único cuando el caso es mixto o cuando la clasificación depende de la anatomía detallada.",
        ),
        FieldSpec(
            "gleason_score",
            "Perfil Gleason / ISUP",
            "gleason_profile",
            default={"gleason_primary": "3", "gleason_secondary": "4", "gleason_tertiary": "", "gleason_score": "7", "isup_grade": "2"},
            group="Carga metastásica",
            group_order=1,
            clinical_role="decision_refiner",
            help_text="Documente patrón primario, secundario y el terciario si existe. El sistema derivará automáticamente el Gleason total y el ISUP para sostener la estratificación clínica.",
        ),
        FieldSpec("rt_primary_received", "Radioterapia local previa", "select", options=["0", "1"], default="0", group="Tratamiento local", group_order=2, clinical_role="required"),
        FieldSpec("ecog_score", "ECOG", "number", default=0, group="Fitness y seguridad", group_order=3, clinical_role="required", unit="0-4"),
        FieldSpec("frailty_status", "Fragilidad clínica", "select", options=["Fit", "Vulnerable", "Frail"], default="Fit", group="Fitness y seguridad", group_order=3, clinical_role="decision_refiner", evidence_tags=["frailty"]),
        FieldSpec("child_pugh_score", "Child-Pugh", "select", options=["A", "B", "C"], default="A", group="Fitness y seguridad", group_order=3, clinical_role="required"),
        FieldSpec("comorbidity_seizure", "Riesgo convulsivo", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="decision_refiner"),
        FieldSpec("comorbidity_cardio", "Riesgo cardiovascular", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="decision_refiner", evidence_tags=["cardio_oncology"]),
        FieldSpec("cv_risk_documented", "Riesgo cardiovascular documentado", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="monitoring", evidence_tags=["cardio_oncology"]),
        FieldSpec("drug_interaction_reviewed", "Interacciones farmacológicas revisadas", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="monitoring", evidence_tags=["drug_interactions"]),
        FieldSpec("current_medications", "Medicaciones concomitantes", "text", default="", group="Fitness y seguridad", group_order=3, clinical_role="decision_refiner", evidence_tags=["drug_interactions"]),
        FieldSpec("dermatitis_history", "Antecedente dermatológico relevante", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="decision_refiner", evidence_tags=["arsi_safety"]),
        FieldSpec("cognitive_risk", "Riesgo cognitivo clínicamente relevante", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="decision_refiner", evidence_tags=["neurotoxicity"]),
        FieldSpec("fall_risk", "Riesgo de caídas", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="decision_refiner", evidence_tags=["falls"]),
        FieldSpec("stroke_history", "Antecedente de EVC/AIT", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="decision_refiner", evidence_tags=["neurovascular"]),
        FieldSpec("edema_risk", "Riesgo de edema / IC", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="decision_refiner", evidence_tags=["cardio_oncology"]),
        FieldSpec("steroid_intolerance", "Intolerancia a esteroides", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="decision_refiner", evidence_tags=["steroids"]),
        FieldSpec("diabetes_uncontrolled", "Diabetes no controlada", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="decision_refiner", evidence_tags=["metabolic_risk"]),
        FieldSpec("hepatic_risk_factors", "Factores de riesgo hepático", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="monitoring", evidence_tags=["hepatotoxicity"]),
        FieldSpec("baseline_bp", "Presión arterial basal sistólica", "number", default="", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", unit="mmHg", evidence_tags=["cardio_oncology"]),
        FieldSpec("baseline_weight", "Peso basal", "number", default="", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", unit="kg", evidence_tags=["qol"]),
        FieldSpec("fatigue_baseline", "Fatiga basal", "number", default="", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", unit="0-10", evidence_tags=["qol"]),
        FieldSpec("neurocognitive_baseline", "Línea basal neurocognitiva", "number", default="", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", unit="puntaje", evidence_tags=["neurotoxicity"]),
        FieldSpec("fall_history_recent", "Caídas recientes", "select", options=["0", "1"], default="0", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", evidence_tags=["falls"]),
        FieldSpec("lft_date", "Fecha de PFH basales", "date", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", evidence_tags=["hepatotoxicity"]),
        FieldSpec("bilirubin", "Bilirrubina total", "number", default="", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", unit="mg/dL", evidence_tags=["hepatotoxicity"]),
        FieldSpec("ast", "AST (TGO)", "number", default="", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", unit="U/L", evidence_tags=["hepatotoxicity"]),
        FieldSpec("alt", "ALT (TGP)", "number", default="", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", unit="U/L", evidence_tags=["hepatotoxicity"]),
        FieldSpec("alp", "Fosfatasa alcalina", "number", default="", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", unit="U/L", evidence_tags=["hepatotoxicity"]),
        FieldSpec("potassium", "Potasio basal", "number", default="", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", unit="mEq/L", evidence_tags=["metabolic_risk"]),
        FieldSpec("glucose_or_hba1c", "Glucosa o HbA1c basal", "number", default="", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", evidence_tags=["metabolic_risk"]),
        FieldSpec("molecular_assay_source", "Fuente del ensayo molecular", "select", options=["Desconocida", "Tejido primario", "Biopsia metastásica", "ctDNA"], default="Desconocida", group="Biomarcadores", group_order=4, clinical_role="decision_refiner", evidence_tags=["biomarkers"]),
        FieldSpec("molecular_assay_date", "Fecha del ensayo molecular", "date", group="Biomarcadores", group_order=4, clinical_role="decision_refiner", evidence_tags=["biomarkers"]),
        FieldSpec("hrr_gene", "Gen HRR predominante", "select", options=["Desconocido", "BRCA2", "BRCA1", "ATM", "PALB2", "CDK12", "Otro"], default="Desconocido", group="Biomarcadores", group_order=4, clinical_role="optional", evidence_tags=["hrr"]),
        FieldSpec("brca2_status", "Estado BRCA2", "select", options=["Desconocido", "Positivo", "Negativo"], default="Desconocido", group="Biomarcadores", group_order=4, clinical_role="decision_refiner", evidence_tags=["hrr"]),
        FieldSpec("dxa_baseline_done", "DXA basal realizada", "select", options=["0", "1"], default="0", group="Salud ósea", group_order=5, clinical_role="monitoring", evidence_tags=["bone_health"]),
        FieldSpec("calcium_vitd_started", "Calcio y vitamina D iniciados", "select", options=["0", "1"], default="0", group="Salud ósea", group_order=5, clinical_role="monitoring", evidence_tags=["bone_health"]),
        FieldSpec("bone_protection_started", "Protección ósea iniciada", "select", options=["0", "1"], default="0", group="Salud ósea", group_order=5, clinical_role="monitoring", evidence_tags=["bone_health"]),
        FieldSpec("rare_histology_variant", "Variante histológica agresiva poco común", "select", options=["0", "1"], default="0", group="Salud ósea", group_order=5, clinical_role="optional", evidence_tags=["variant_histology"]),
        FieldSpec("neuroendocrine_features", "Rasgos neuroendocrinos emergentes", "select", options=["0", "1"], default="0", group="Salud ósea", group_order=5, clinical_role="optional", evidence_tags=["variant_histology"]),
        FieldSpec("baseline_qol", "Calidad de vida basal", "number", default=75, group="Resultados reportados por el paciente", group_order=4, clinical_role="monitoring", unit="0-100", evidence_tags=["qol"]),
    ],
)
