from __future__ import annotations

from prostanet.shared.contracts import FieldSpec, module_schema


M1_CRPC_SCHEMA = module_schema(
    "m1_crpc",
    "M1 CRPC",
    "Ruta de enfermedad resistente a la castración con metástasis, dirigida por biomarcadores, secuencia terapéutica y elegibilidad estructurada a taxanos.",
    fields=[
        FieldSpec("hrr_status", "Estado HRR", "select", options=["Desconocido", "Positivo", "Negativo"], default="Desconocido", group="Biomarcadores", group_order=1, clinical_role="required", evidence_tags=["hrr"]),
        FieldSpec("hrr_gene", "Gen HRR predominante", "select", options=["Desconocido", "BRCA2", "BRCA1", "ATM", "PALB2", "CDK12", "Otro"], default="Desconocido", group="Biomarcadores", group_order=1, clinical_role="decision_refiner", evidence_tags=["hrr"]),
        FieldSpec("msi_status", "Estado MSI", "select", options=["desconocido", "inestable", "estable"], default="desconocido", group="Biomarcadores", group_order=1, clinical_role="decision_refiner", evidence_tags=["msi"]),
        FieldSpec("tmb_high", "Carga mutacional tumoral alta", "select", options=["0", "1"], default="0", group="Biomarcadores", group_order=1, clinical_role="optional", evidence_tags=["tmb"]),
        FieldSpec("biomarker_source", "Fuente del biomarcador", "select", options=["Desconocida", "Tejido primario", "Biopsia metastásica", "ctDNA"], default="Desconocida", group="Biomarcadores", group_order=1, clinical_role="required", evidence_tags=["hrr", "msi", "vision"]),
        FieldSpec("molecular_report_date", "Fecha del informe molecular", "date", group="Biomarcadores", group_order=1, clinical_role="decision_refiner", evidence_tags=["molecular_traceability"]),
        FieldSpec("metastasis_site", "Sitio metastásico", "select", options=["Bone", "Node", "Visceral"], default="Bone", group="Carga tumoral", group_order=2, clinical_role="required"),
        FieldSpec("prior_therapy", "Terapias previas", "text", default="Abiraterona", group="Secuencia terapéutica", group_order=3, clinical_role="required", evidence_tags=["sequence"]),
        FieldSpec("prior_docetaxel_cycles", "Ciclos previos de docetaxel", "number", default=0, group="Secuencia terapéutica", group_order=3, clinical_role="required", unit="ciclos"),
        FieldSpec("prior_arpi_duration_months", "Duración de ARPI previo", "number", default="", group="Secuencia terapéutica", group_order=3, clinical_role="decision_refiner", unit="meses", evidence_tags=["sequence", "card"]),
        FieldSpec("castrate_testosterone_confirmed", "Testosterona en rango de castración confirmada", "select", options=["0", "1"], default="1", group="Secuencia terapéutica", group_order=3, clinical_role="required", evidence_tags=["castration_confirmation"]),
        FieldSpec("mcrpc_line_context", "Contexto de línea en mCRPC", "select", options=["first_line_mcrpc", "post_arpi_pre_taxane", "post_taxane", "later_line"], default="first_line_mcrpc", group="Secuencia terapéutica", group_order=3, clinical_role="required", evidence_tags=["sequence"]),
        FieldSpec("chemotherapy_delay_candidate", "Candidato a diferir o evitar docetaxel", "select", options=["0", "1"], default="0", group="Secuencia terapéutica", group_order=3, clinical_role="decision_refiner", evidence_tags=["sequence"]),
        FieldSpec("pain_symptoms", "Síntomas óseos / dolor", "select", options=["Asintomatico", "Leve", "Sintomatico"], default="Asintomatico", group="Secuencia terapéutica", group_order=3, clinical_role="decision_refiner", evidence_tags=["symptoms"]),
        FieldSpec("soft_tissue_metastases", "Metástasis en partes blandas", "select", options=["0", "1"], default="0", group="Secuencia terapéutica", group_order=3, clinical_role="decision_refiner", evidence_tags=["contact_02"]),
        FieldSpec("bone_modifying_agent", "Agente modificador óseo activo", "select", options=["0", "1"], default="0", group="Secuencia terapéutica", group_order=3, clinical_role="monitoring", evidence_tags=["bone_health", "peace_3"]),
        FieldSpec("ecog_score", "ECOG", "number", default=1, group="Fitness y seguridad", group_order=4, clinical_role="required", unit="0-4"),
        FieldSpec("frailty_status", "Fragilidad clínica", "select", options=["Fit", "Vulnerable", "Frail"], default="Fit", group="Fitness y seguridad", group_order=4, clinical_role="decision_refiner", evidence_tags=["frailty"]),
        FieldSpec("child_pugh_score", "Child-Pugh", "select", options=["A", "B", "C"], default="A", group="Fitness y seguridad", group_order=4, clinical_role="decision_refiner", evidence_tags=["hepatotoxicity"]),
        FieldSpec("comorbidity_seizure", "Riesgo convulsivo", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=4, clinical_role="decision_refiner", evidence_tags=["arsi_safety"]),
        FieldSpec("comorbidity_cardio", "Riesgo cardiovascular", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=4, clinical_role="decision_refiner", evidence_tags=["cardio_oncology"]),
        FieldSpec("peripheral_neuropathy_grade", "Neuropatía periférica", "select", options=["0", "1", "2", "3", "4"], default="0", group="Fitness y seguridad", group_order=4, clinical_role="decision_refiner", unit="CTCAE"),
        FieldSpec("rare_histology_variant", "Variante histológica agresiva poco común", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=4, clinical_role="optional", evidence_tags=["variant_histology"]),
        FieldSpec("neuroendocrine_features", "Rasgos neuroendocrinos emergentes", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=4, clinical_role="optional", evidence_tags=["variant_histology"]),
        FieldSpec("cv_risk_documented", "Riesgo cardiovascular documentado", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=4, clinical_role="monitoring", evidence_tags=["cardio_oncology"]),
        FieldSpec("drug_interaction_reviewed", "Interacciones farmacológicas revisadas", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=4, clinical_role="monitoring", evidence_tags=["drug_interactions"]),
        FieldSpec("current_medications", "Medicaciones concomitantes", "text", default="", group="Fitness y seguridad", group_order=4, clinical_role="decision_refiner", evidence_tags=["drug_interactions"]),
        FieldSpec("dermatitis_history", "Antecedente dermatológico relevante", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=4, clinical_role="decision_refiner", evidence_tags=["arsi_safety"]),
        FieldSpec("cognitive_risk", "Riesgo cognitivo clínicamente relevante", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=4, clinical_role="decision_refiner", evidence_tags=["neurotoxicity"]),
        FieldSpec("fall_risk", "Riesgo de caídas", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=4, clinical_role="decision_refiner", evidence_tags=["falls"]),
        FieldSpec("stroke_history", "Antecedente de EVC/AIT", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=4, clinical_role="decision_refiner", evidence_tags=["neurovascular"]),
        FieldSpec("edema_risk", "Riesgo de edema / IC", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=4, clinical_role="decision_refiner", evidence_tags=["cardio_oncology"]),
        FieldSpec("steroid_intolerance", "Intolerancia a esteroides", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=4, clinical_role="decision_refiner", evidence_tags=["steroids"]),
        FieldSpec("diabetes_uncontrolled", "Diabetes no controlada", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=4, clinical_role="decision_refiner", evidence_tags=["metabolic_risk"]),
        FieldSpec("hepatic_risk_factors", "Factores de riesgo hepático", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=4, clinical_role="monitoring", evidence_tags=["hepatotoxicity"]),
        FieldSpec("baseline_bp", "Presión arterial basal sistólica", "number", default="", group="Monitoreo basal ARPI", group_order=5, clinical_role="monitoring", unit="mmHg", evidence_tags=["cardio_oncology"]),
        FieldSpec("baseline_weight", "Peso basal", "number", default="", group="Monitoreo basal ARPI", group_order=5, clinical_role="monitoring", unit="kg", evidence_tags=["qol"]),
        FieldSpec("fatigue_baseline", "Fatiga basal", "number", default="", group="Monitoreo basal ARPI", group_order=5, clinical_role="monitoring", unit="0-10", evidence_tags=["qol"]),
        FieldSpec("neurocognitive_baseline", "Línea basal neurocognitiva", "number", default="", group="Monitoreo basal ARPI", group_order=5, clinical_role="monitoring", unit="puntaje", evidence_tags=["neurotoxicity"]),
        FieldSpec("fall_history_recent", "Caídas recientes", "select", options=["0", "1"], default="0", group="Monitoreo basal ARPI", group_order=5, clinical_role="monitoring", evidence_tags=["falls"]),
        FieldSpec("potassium", "Potasio basal", "number", default="", group="Monitoreo basal ARPI", group_order=5, clinical_role="monitoring", unit="mEq/L", evidence_tags=["metabolic_risk"]),
        FieldSpec("glucose_or_hba1c", "Glucosa o HbA1c basal", "number", default="", group="Monitoreo basal ARPI", group_order=5, clinical_role="monitoring", evidence_tags=["metabolic_risk"]),
        FieldSpec("cbc_date", "Fecha de biometría hemática", "date", group="Elegibilidad taxano", group_order=5, clinical_role="decision_refiner", evidence_tags=["taxane_fitness"], conditional_visibility={"prior_docetaxel_cycles": ["0"]}),
        FieldSpec("anc", "Neutrófilos absolutos", "number", group="Elegibilidad taxano", group_order=5, clinical_role="decision_refiner", unit="/mm3", evidence_tags=["taxane_fitness"], conditional_visibility={"prior_docetaxel_cycles": ["0"]}),
        FieldSpec("platelets", "Plaquetas", "number", group="Elegibilidad taxano", group_order=5, clinical_role="decision_refiner", unit="/mm3", evidence_tags=["taxane_fitness"], conditional_visibility={"prior_docetaxel_cycles": ["0"]}),
        FieldSpec("hemoglobin", "Hemoglobina", "number", group="Elegibilidad taxano", group_order=5, clinical_role="decision_refiner", unit="g/dL", evidence_tags=["parp", "taxane_fitness"], conditional_visibility={"prior_docetaxel_cycles": ["0"]}),
        FieldSpec("bone_marrow_reserve_concern", "Reserva medular comprometida", "select", options=["0", "1"], default="0", group="Elegibilidad taxano", group_order=5, clinical_role="decision_refiner", evidence_tags=["parp", "taxane_fitness"], conditional_visibility={"prior_docetaxel_cycles": ["0"]}),
        FieldSpec("liver_panel_date", "Fecha de pruebas hepáticas", "date", group="Elegibilidad taxano", group_order=5, clinical_role="decision_refiner", evidence_tags=["taxane_fitness"], conditional_visibility={"prior_docetaxel_cycles": ["0"]}),
        FieldSpec("bilirubin", "Bilirrubina total", "number", group="Elegibilidad taxano", group_order=5, clinical_role="decision_refiner", unit="mg/dL", evidence_tags=["taxane_fitness"], conditional_visibility={"prior_docetaxel_cycles": ["0"]}),
        FieldSpec("ast", "AST", "number", group="Elegibilidad taxano", group_order=5, clinical_role="decision_refiner", unit="U/L", evidence_tags=["taxane_fitness"], conditional_visibility={"prior_docetaxel_cycles": ["0"]}),
        FieldSpec("alt", "ALT", "number", group="Elegibilidad taxano", group_order=5, clinical_role="decision_refiner", unit="U/L", evidence_tags=["taxane_fitness"], conditional_visibility={"prior_docetaxel_cycles": ["0"]}),
        FieldSpec("alp", "Fosfatasa alcalina", "number", group="Elegibilidad taxano", group_order=5, clinical_role="decision_refiner", unit="U/L", evidence_tags=["taxane_fitness"], conditional_visibility={"prior_docetaxel_cycles": ["0"]}),
        FieldSpec("taxane_hypersensitivity_history", "Hipersensibilidad previa a taxanos", "select", options=["0", "1"], default="0", group="Elegibilidad taxano", group_order=5, clinical_role="decision_refiner", evidence_tags=["taxane_fitness"], conditional_visibility={"prior_docetaxel_cycles": ["0"]}),
        FieldSpec("polysorbate_hypersensitivity", "Hipersensibilidad a polisorbato 80", "select", options=["0", "1"], default="0", group="Elegibilidad taxano", group_order=5, clinical_role="decision_refiner", evidence_tags=["taxane_fitness"], conditional_visibility={"prior_docetaxel_cycles": ["0"]}),
        FieldSpec("strong_cyp3a_inhibitor", "Inhibidor potente CYP3A concomitante", "select", options=["0", "1"], default="0", group="Elegibilidad taxano", group_order=5, clinical_role="decision_refiner", evidence_tags=["drug_interactions"], conditional_visibility={"prior_docetaxel_cycles": ["0"]}),
        FieldSpec("egfr", "eGFR / depuración creatinina", "number", group="Elegibilidad taxano", group_order=5, clinical_role="decision_refiner", unit="mL/min", evidence_tags=["parp", "renal_function"], conditional_visibility={"prior_docetaxel_cycles": ["0"]}),
        FieldSpec("psma_positive", "PSMA positivo", "select", options=["0", "1"], default="0", group="Imagen funcional", group_order=6, clinical_role="required", evidence_tags=["vision"]),
        FieldSpec("psma_negative_dominant_lesions", "Lesiones dominantes PSMA-negativas", "select", options=["0", "1"], default="0", group="Imagen funcional", group_order=6, clinical_role="decision_refiner", evidence_tags=["vision"]),
        FieldSpec("psma_pet_done", "PSMA-PET estructurado disponible", "select", options=["0", "1"], default="0", group="Imagen funcional", group_order=6, clinical_role="decision_refiner", evidence_tags=["vision"]),
        FieldSpec("psma_radioligand", "Radioligando PSMA", "select", options=["68Ga-PSMA-11", "18F-DCFPyL", "18F-PSMA-1007", "Otro", "Desconocido"], default="Desconocido", group="Imagen funcional", group_order=6, clinical_role="decision_refiner", evidence_tags=["vision"], conditional_visibility={"psma_pet_done": ["1"]}),
        FieldSpec("psma_index_lesion_site", "Lesión índice PSMA", "text", group="Imagen funcional", group_order=6, clinical_role="decision_refiner", conditional_visibility={"psma_pet_done": ["1"]}),
        FieldSpec("psma_index_lesion_suvmax", "SUVmax lesión índice", "number", group="Imagen funcional", group_order=6, clinical_role="decision_refiner", unit="SUV", conditional_visibility={"psma_pet_done": ["1"]}),
        FieldSpec("psma_uptake_pattern", "Patrón de captación", "select", options=["focal", "multifocal", "diseminado", "indeterminado"], default="indeterminado", group="Imagen funcional", group_order=6, clinical_role="decision_refiner", conditional_visibility={"psma_pet_done": ["1"]}),
        FieldSpec("psma_rads_score", "PSMA-RADS", "select", options=["1", "2", "3", "4", "5", "Desconocido"], default="Desconocido", group="Imagen funcional", group_order=6, clinical_role="decision_refiner", conditional_visibility={"psma_pet_done": ["1"]}),
        FieldSpec("psma_total_lesions", "Número total de lesiones PSMA", "number", group="Imagen funcional", group_order=6, clinical_role="decision_refiner", conditional_visibility={"psma_pet_done": ["1"]}),
        FieldSpec("psma_lesion_locations", "Localización de lesiones PSMA", "text", group="Imagen funcional", group_order=6, clinical_role="decision_refiner", conditional_visibility={"psma_pet_done": ["1"]}),
        FieldSpec("baseline_qol", "Calidad de vida basal", "number", default=65, group="Resultados reportados por el paciente", group_order=7, clinical_role="monitoring", unit="0-100", evidence_tags=["qol"]),
    ],
)
