from __future__ import annotations

from prostanet.shared.contracts import FieldSpec, module_schema


M0_CRPC_SCHEMA = module_schema(
    "m0_crpc",
    "M0 CRPC",
    "Ruta de intensificación adaptada al riesgo en enfermedad resistente a la castración sin metástasis, con discriminación explícita de seguridad entre ARPI.",
    fields=[
        FieldSpec("psadt_months", "Tiempo de duplicación del PSA", "number", required=True, default=7, group="Riesgo oncológico", group_order=1, clinical_role="required", unit="meses", evidence_tags=["psa_kinetics"]),
        FieldSpec("castration_resistant", "Resistente a la castración", "select", required=True, options=["1"], default="1", group="Riesgo oncológico", group_order=1, clinical_role="required"),
        FieldSpec("imaging_negative", "Imagen negativa", "select", options=["0", "1"], default="1", group="Riesgo oncológico", group_order=1, clinical_role="required"),
        FieldSpec("castrate_testosterone_confirmed", "Testosterona en rango de castración confirmada", "select", options=["0", "1"], default="1", group="Riesgo oncológico", group_order=1, clinical_role="required", evidence_tags=["castration_confirmation"]),
        FieldSpec("conventional_imaging_modality", "Modalidad de imagen convencional", "select", options=["Desconocida", "TC + gammagrama óseo", "TC sola", "RM", "PET/CT", "Otra"], default="Desconocida", group="Riesgo oncológico", group_order=1, clinical_role="decision_refiner", evidence_tags=["restaging"]),
        FieldSpec("conventional_imaging_date", "Fecha de imagen convencional", "date", group="Riesgo oncológico", group_order=1, clinical_role="decision_refiner", evidence_tags=["restaging"]),
        FieldSpec("ecog_score", "ECOG", "number", default=1, group="Seguridad y tolerabilidad", group_order=2, clinical_role="required", unit="0-4", evidence_tags=["performance_status"]),
        FieldSpec("comorbidity_seizure", "Riesgo convulsivo", "select", options=["0", "1"], default="0", group="Seguridad y tolerabilidad", group_order=2, clinical_role="decision_refiner", evidence_tags=["arsi_safety"]),
        FieldSpec("comorbidity_cardio", "Riesgo cardiovascular", "select", options=["0", "1"], default="0", group="Seguridad y tolerabilidad", group_order=2, clinical_role="decision_refiner", evidence_tags=["cardio_oncology"]),
        FieldSpec("frailty_status", "Fragilidad clínica", "select", options=["Fit", "Vulnerable", "Frail"], default="Fit", group="Seguridad y tolerabilidad", group_order=2, clinical_role="decision_refiner", evidence_tags=["frailty"]),
        FieldSpec("child_pugh_score", "Child-Pugh", "select", options=["A", "B", "C"], default="A", group="Seguridad y tolerabilidad", group_order=2, clinical_role="required", evidence_tags=["hepatotoxicity"]),
        FieldSpec("hepatic_risk_factors", "Factores de riesgo hepático", "select", options=["0", "1"], default="0", group="Seguridad y tolerabilidad", group_order=2, clinical_role="decision_refiner", evidence_tags=["hepatotoxicity"]),
        FieldSpec("cv_risk_documented", "Riesgo cardiovascular documentado", "select", options=["0", "1"], default="0", group="Seguridad y tolerabilidad", group_order=2, clinical_role="monitoring", evidence_tags=["cardio_oncology"]),
        FieldSpec("drug_interaction_reviewed", "Interacciones farmacológicas revisadas", "select", options=["0", "1"], default="0", group="Seguridad y tolerabilidad", group_order=2, clinical_role="monitoring", evidence_tags=["drug_interactions"]),
        FieldSpec("current_medications", "Medicaciones concomitantes", "text", default="", group="Seguridad y tolerabilidad", group_order=2, clinical_role="decision_refiner", evidence_tags=["drug_interactions"]),
        FieldSpec("dermatitis_history", "Antecedente dermatológico relevante", "select", options=["0", "1"], default="0", group="Seguridad y tolerabilidad", group_order=2, clinical_role="decision_refiner", evidence_tags=["arsi_safety"]),
        FieldSpec("cognitive_risk", "Riesgo cognitivo clínicamente relevante", "select", options=["0", "1"], default="0", group="Seguridad y tolerabilidad", group_order=2, clinical_role="decision_refiner", evidence_tags=["neurotoxicity"]),
        FieldSpec("fall_risk", "Riesgo de caídas", "select", options=["0", "1"], default="0", group="Seguridad y tolerabilidad", group_order=2, clinical_role="decision_refiner", evidence_tags=["falls"]),
        FieldSpec("stroke_history", "Antecedente de EVC/AIT", "select", options=["0", "1"], default="0", group="Seguridad y tolerabilidad", group_order=2, clinical_role="decision_refiner", evidence_tags=["neurovascular"]),
        FieldSpec("edema_risk", "Riesgo de edema / insuficiencia cardiaca", "select", options=["0", "1"], default="0", group="Seguridad y tolerabilidad", group_order=2, clinical_role="decision_refiner", evidence_tags=["cardio_oncology"]),
        FieldSpec("steroid_intolerance", "Intolerancia a esteroides", "select", options=["0", "1"], default="0", group="Seguridad y tolerabilidad", group_order=2, clinical_role="decision_refiner", evidence_tags=["steroids"]),
        FieldSpec("diabetes_uncontrolled", "Diabetes no controlada", "select", options=["0", "1"], default="0", group="Seguridad y tolerabilidad", group_order=2, clinical_role="decision_refiner", evidence_tags=["metabolic_risk"]),
        FieldSpec("baseline_bp", "Presión arterial basal sistólica", "number", default="", group="Monitoreo basal ARPI", group_order=3, clinical_role="monitoring", unit="mmHg", evidence_tags=["arsi_safety"]),
        FieldSpec("baseline_weight", "Peso basal", "number", default="", group="Monitoreo basal ARPI", group_order=3, clinical_role="monitoring", unit="kg", evidence_tags=["qol"]),
        FieldSpec("fatigue_baseline", "Fatiga basal", "number", default="", group="Monitoreo basal ARPI", group_order=3, clinical_role="monitoring", unit="0-10", evidence_tags=["qol"]),
        FieldSpec("neurocognitive_baseline", "Línea basal neurocognitiva", "number", default="", group="Monitoreo basal ARPI", group_order=3, clinical_role="monitoring", unit="puntaje", evidence_tags=["neurotoxicity"]),
        FieldSpec("fall_history_recent", "Caídas recientes", "select", options=["0", "1"], default="0", group="Monitoreo basal ARPI", group_order=3, clinical_role="monitoring", evidence_tags=["falls"]),
        FieldSpec("lft_date", "Fecha de PFH basales", "date", group="Monitoreo basal ARPI", group_order=3, clinical_role="monitoring", evidence_tags=["hepatotoxicity"]),
        FieldSpec("bilirubin", "Bilirrubina total", "number", default="", group="Monitoreo basal ARPI", group_order=3, clinical_role="monitoring", unit="mg/dL", evidence_tags=["hepatotoxicity"]),
        FieldSpec("ast", "AST (TGO)", "number", default="", group="Monitoreo basal ARPI", group_order=3, clinical_role="monitoring", unit="U/L", evidence_tags=["hepatotoxicity"]),
        FieldSpec("alt", "ALT (TGP)", "number", default="", group="Monitoreo basal ARPI", group_order=3, clinical_role="monitoring", unit="U/L", evidence_tags=["hepatotoxicity"]),
        FieldSpec("alp", "Fosfatasa alcalina", "number", default="", group="Monitoreo basal ARPI", group_order=3, clinical_role="monitoring", unit="U/L", evidence_tags=["hepatotoxicity"]),
        FieldSpec("potassium", "Potasio basal", "number", default="", group="Monitoreo basal ARPI", group_order=3, clinical_role="monitoring", unit="mEq/L", evidence_tags=["metabolic_risk"]),
        FieldSpec("glucose_or_hba1c", "Glucosa o HbA1c basal", "number", default="", group="Monitoreo basal ARPI", group_order=3, clinical_role="monitoring", evidence_tags=["metabolic_risk"]),
        FieldSpec("baseline_qol", "Calidad de vida basal", "number", default=70, group="Resultados reportados por el paciente", group_order=4, clinical_role="monitoring", unit="0-100", evidence_tags=["qol"]),
    ],
)
